## Random Forest Regression

In [1]:
# STEP 1
# 훈련 데이터셋 중 K개의 랜덤 데이터를 선택한다.

# STEP 2
# K개의 데이터를 가지고 의사 결정 트리를 구축한다.

# STEP 3
# STEP1,2 반복 및 만들고자 하는 트리의 수를 결정한다

#STEP 4
# 해당 데이터 포인트에 대한 y값을 예측하고 예측된 모든 y값에 대한 평균 데이터 포인터를 찾는다. (multiple prediction)

## Importing the LB

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

### Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0) 

## Training the Random Forest Regression Model on the Training Set

In [7]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

## Predicting the Test set results

In [8]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1), y_test.reshape(len(y_test),1)),1))

[[434.32 431.23 431.23]
 [458.12 460.01 460.01]
 [469.48 461.14 461.14]
 ...
 [472.52 473.26 473.26]
 [440.09 438.   438.  ]
 [463.56 463.28 463.28]]


In [9]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9350010938497556